// <auto-generated />
namespace WebsiteZft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addjob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjob));
        
        string IMigrationMetadata.Id
        {
            get { return "202004192101093_addjob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
